theme: jekyll-theme-minimal
title: Nim macro documentation
description: Here I present all information about macros in the Nim language, both as an educational tutorial and a reference for my purposes.

